import assert from 'node:assert/strict';
const base=process.env.IBYARA_TEST_ORIGIN??'http://127.0.0.1:4173';
assert.ok(new URL(base).hostname==='127.0.0.1'||new URL(base).hostname==='localhost','This test suite uses disposable development identities; local server only.');
const owner=`test_${crypto.randomUUID()}`;
const request=async(path,body,key=crypto.randomUUID(),identity=owner)=>{const res=await fetch(`${base}/api/v1/${path}`,{method:body?'POST':'GET',headers:{'oai-authenticated-user-id':identity,'Content-Type':'application/json','Idempotency-Key':key},body:body?JSON.stringify(body):undefined});return {status:res.status,body:await res.json()};};
const cmd=async(body,key,identity)=>{const r=await request('commands',body,key,identity);assert.equal(r.status,200,JSON.stringify(r.body));return r.body;};
const initial=await request('state?role=merchant');assert.equal(initial.status,200,JSON.stringify(initial.body));
await cmd({type:'seed_demo',scope:'merchant'});
const merchant=await request('state?role=merchant');assert.equal(merchant.body.restaurant.recipes[0].pricing.floorCents,2618);
const m=await cmd({type:'mandate',scope:'buyer',maxCents:3500,description:'Bife a cavalo',maxMinutes:40,zone:'demo_butanta',excluded:[],confirmed:true});
const q=await cmd({type:'rfq',scope:'buyer',mandateId:m.result.mandateId});assert.equal(q.state.offers.length,3);
const key=crypto.randomUUID(),purchase={type:'negotiate',scope:'buyer',rfqId:q.result.rfqId};
const results=await Promise.all([cmd(purchase,key),cmd(purchase,key)]);
assert.equal(results[0].state.orders[0].id,results[1].state.orders[0].id);assert.equal(results[0].state.orders[0].totalCents,3090);assert.ok(results.some(r=>r.replayed));
const after=await request('state?role=merchant');assert.equal(after.body.orders.length,1);assert.equal(after.body.restaurant.stock[0].reserved,'200');
const conflict=await request('commands',{...purchase,rfqId:'other'},key);assert.equal(conflict.status,409);assert.equal(conflict.body.error.code,'IDEMPOTENCY_CONFLICT');
const tampered=await request('commands',{type:'accept',scope:'buyer',offerId:'x',quoteToken:'y',totalCents:1});assert.equal(tampered.status,422);assert.equal(tampered.body.error.code,'INVALID_COMMAND');
const second=await request('state?role=merchant',undefined,undefined,`test_${crypto.randomUUID()}`);assert.equal(second.body.restaurant.recipes.length,0);assert.equal(second.body.orders.length,0);
const buyer=await request('state?role=buyer');assert.ok(!JSON.stringify(buyer.body).includes('floorCents'));assert.ok(!JSON.stringify(buyer.body).includes('stockSnapshot'));
const response=await fetch(`${base}/api/v1/events?role=buyer&after=0`,{headers:{'oai-authenticated-user-id':owner}});const events=await response.text();assert.match(events,/ORDER_CONFIRMED/);assert.ok(!events.includes('floorCents'));
const orderId=after.body.orders[0].id;await cmd({type:'order',scope:'merchant',orderId,action:'prepare'});await cmd({type:'order',scope:'merchant',orderId,action:'prepare'});const consumed=await request('state?role=merchant');assert.equal(consumed.body.restaurant.stock[0].quantity,'5800');assert.equal(consumed.body.restaurant.stock[0].reserved,'0');
console.log(JSON.stringify({status:'PASS',checks:['D1 persistence','canonical 3090-cent order','simultaneous idempotent retries','idempotency conflict','extra financial fields rejected','owner isolation','buyer redaction','SSE replay','consume once'],realPayments:false},null,2));
